kubeProxyReplacement: true
k8sServiceHost: kind-control-plane
k8sServicePort: 6443
debug:
  enabled: true
operator:
  replicas: 1
hubble:
  enabled: true
  ui:
    enabled: true
  relay:
    enabled: true

