kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
    service:
      type: LoadBalancer
      port: 80
  grafana:
    adminPassword: admin
    service:
      type: LoadBalancer

