cilium:
  kubeProxyReplacement: true
  k8sServiceHost: kind-control-plane
  k8sServicePort: 6443
  operator:
    replicas: 1
  l2announcements:
    enabled: true
  hubble:
    enabled: true
    ui:
      enabled: true
      service:
        type: LoadBalancer
        port: 8080
    relay:
      enabled: true

