cilium:
  kubeProxyReplacement: true
  k8sServiceHost: kind-control-plane
  k8sServicePort: 6443
  operator:
    replicas: 1
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
  l2announcements:
    enabled: true
  hubble:
    enabled: true
    ui:
      enabled: true
      service:
        type: LoadBalancer
        port: 8080
    relay:
      enabled: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
    metrics:
      enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - icmp
      - http
      serviceMonitor:
        enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      trustCRDsExist: true

